config/routes.rb
Rails.application.routes.draw do

  get 'startup/index'
  resources :careservices
  resources :services, only: [:show]
  resources :caregivers


  resources :appointments
  resources :dogs
  resources :users

  # to get the login form
    get '/login', to: "sessions#login", as: "login" # does this match REST? where does this go?
    # we need to create a session saying we are logged in
    post '/sessions', to: "sessions#create"
    #get '/logout', to: "sessions#destroy"  as: "logout"

    get 'new30mwalk', to: "appointments#new_30m_walk", as: "new30mwalk"
    get 'new1hrwalk', to: "appointments#new_1hr_walk", as: "new1hrwalk"
    get 'newovernight', to: "appointments#new_overnight", as: "newovernight"
    get 'newgrooming', to: "appointments#new_grooming", as: "newgrooming"
    get 'newvet', to: "appointments#new_vet", as: "newvet"
    delete 'logout', to: "sessions#destroy"

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :dog
  belongs_to :caregiver
  belongs_to :service

def find_dog
  id = self.dog_id
  Dog.all.find_by(id: id)
end

def find_caregiver
  id = self.caregiver_id
  Caregiver.all.find_by(id: id)
end

def find_service
  id = self.service_id
  Service.all.find_by(id: id)
end

end

app/models/caregiver.rb
class Caregiver < ApplicationRecord
  has_many :careservices, dependent: :destroy
  has_many :services, through: :careservices
  has_many :appointments

  validates :name, presence: true
  validates :bio, presence: true
  validates :neighborhood, presence: true


end

app/models/careservice.rb
class Careservice < ApplicationRecord
  belongs_to :caregiver
  belongs_to :service

end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  has_many :appointments, dependent: :destroy
  has_many :caregivers, through: :appointments
  has_many :services, through: :appointments

  validates :name, presence: true
  validates :age, numericality: true
  validates :size, inclusion: { in: %w(small medium large),
    message: "%{value} is not a valid size- input small, medium or large." }
  validates :vet_name, presence: true
  validates :food_name, presence: true

end

app/models/service.rb
class Service < ApplicationRecord
  has_many :careservices, dependent: :destroy
  has_many :caregivers, through: :careservices
  has_many :appointments
  # has_many :appointments


  def halfwalk_caregivers
    Service.first.caregivers
  end

  def fullwalk_caregivers
    Service.second.caregivers
  end

  def dogsit_caregivers
    Service.third.caregivers
  end

  def grooming_caregivers
    Service.fourth.caregivers
  end

  def vet_caregivers
    Service.fifth.caregivers
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :dogs, dependent: :destroy
  accepts_nested_attributes_for :dogs
  has_many :appointments, through: :dogs

  validates :full_name, presence: true
  validates :email, uniqueness: true
  validates :phone_number, numericality: {only_integer: true}
  validates :neighborhood, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorize

    def authorize
      if !User.find_by(id: session[:user_id])
        # redirect_to login_path
      end
    end

  end

app/controllers/caregivers_controller.rb
class CaregiversController < ApplicationController

  def index
    @caregivers = Caregiver.all
  end

  def show
    @caregiver = Caregiver.find(params[:id])
  end

  def new
    @caregiver = Caregiver.new
  end

  def create
    @caregiver = Caregiver.create(caregiver_params)
    if @caregiver.valid?
      redirect_to caregiver_path(@caregiver)
    else
      flash[:errors] = @caregiver.errors.full_messages
      redirect_to new_caregiver_path
    end
  end

  def edit
    @caregiver = Caregiver.find(params[:id])
  end

  def update
    @caregiver = Caregiver.find(params[:id])
    @caregiver.update(caregiver_params)
    redirect_to caregiver_path(@caregiver)
  end

  def destroy
    @caregiver = Caregiver.find(params[:id])
    @caregiver.destroy
    redirect_to caregivers_path
  end

  private

  def caregiver_params
    params.require(:caregiver).permit(:name, :bio, :neighborhood, service_id: [])
  end

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
      @dogs = Dog.all
    end

    def show
      @dog = Dog.find(params[:id])
      @appointments = @dog.appointments
    end

    def new
      @dog = Dog.new
    end

  def create
    @dog = Dog.create(dog_params)
    if @dog.valid?
      redirect_to dog_path(@dog)
    else
      flash[:errors] = @dog.errors.full_messages
      redirect_to new_dog_path
      end
    end

    def edit
      @dog = Dog.find(params[:id])
    end

    def update
      @dog = Dog.find(params[:id])
      @dog.update(dog_params)
        redirect_to dog_path(@dog)
    end

    def destroy
      @dog = Dog.find(params[:id])
      @dog.destroy
      redirect_to dogs_path
    end

    private
    def dog_params
      params.require(:dog).permit(:name, :age, :size, :vet_name, :food_name, :user_id, :img_url)
    end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def show
    @service = Service.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize, only: [:login, :create]

  def login
    @halfhrwalk = Service.find_by(id: 6)
    @hrwalk = Service.find_by(id: 7)
    @overnight = Service.find_by(id: 8)
    @groom = Service.find_by(id: 9)
    @vet = Service.find_by(id: 10)
  end

  def create
    @user = User.find_by(username: params[:username])
    if !!@user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:unauthenticated] = "Not Authenticated"
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end


end

app/controllers/startup_controller.rb
class StartupController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:show, :new]


  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @dogs = @user.dogs.all
    # @appointments = @dogs
  end

  def new
    @user = User.new
    @user.dogs.build
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      redirect_to @user
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find(params[:id])
    @dogs = Dog.all
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to @user
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path

  end

  def add_dog
    @user.dogs << Dog.create
  end

  # def logout
  #   session[:user_id].delete
  #   redirect_to
  # end

  private

  def user_params
    params.require(:user).permit(:username, :password, :full_name, :email, :phone_number, :neighborhood,
    dogs_attributes:[
      :name, :age, :size, :vet_name, :food_name, :img_url
    ])
  end

 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/caregivers_helper.rb
module CaregiversHelper
end

app/helpers/careservices_helper.rb
module CareservicesHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/startup_helper.rb
module StartupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/caregivers/_form.erb
<%= form_for(@caregiver) do |f| %>
  <div class="field">
    <%= f.label :name %>:
    <%= f.text_field :name %><br>
    <%= f.label :bio %>:
    <%= f.text_area :bio %><br>
    <%= f.label :neighborhood %>:
    <%= f.text_field :neighborhood %><br>
    <%= f.label :picture %>:
    <%= f.url_field :picture_url %><br>
  </div>

  <div>
    <% Service.all.each do |service| %>
      <%= check_box_tag "caregiver[service_ids][]", service.id, f.object.services.include?(service) %>
      <%= service.name %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/caregivers/edit.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <title>Login</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

body {
  text-align: center;
  font-family: Arial, Helvetica, sans-serif;
  color:  seagreen;
  font-size: 25px;
}

/* Style the header */
.header {
  background-color: #f1f1f1;
  padding: 30px;
  text-align: left;
  font-size: 10px;
}

/* Create three equal columns that floats next to each other */
.column {
  /*float: left;*/
  width: 20%;
  padding: 10px;
  height: 300px; /* Should be removed. Only for demonstration */
  border: 2px solid green;
  border-radius: 12px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Style the footer */
.footer {
  background-color: #f1f1f1;
  padding: 10px;
  text-align: right;
  font-size: 10px;
}
#box{
    display: block;
    margin-left: auto;
  margin-right: auto;
  width: 80%;
    height: 50%;
    background:#f1f1f1;
    border: 2px solid green;
    border-radius: 12px;

}
img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}


/* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
@media (max-width: 600px) {
  .column {
    width: 100%;
  }
}
</style>
<div id="box"><!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <title>Login</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

body {
  text-align: center;
  font-family: Arial, Helvetica, sans-serif;
  color:  seagreen;
  font-size: 25px;
}

/* Style the header */
.header {
  background-color: #f1f1f1;
  padding: 30px;
  text-align: left;
  font-size: 10px;
}

/* Create three equal columns that floats next to each other */
.column {
  /*float: left;*/
  width: 20%;
  padding: 10px;
  height: 300px; /* Should be removed. Only for demonstration */
  border: 2px solid green;
  border-radius: 12px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Style the footer */
.footer {
  background-color: #f1f1f1;
  padding: 10px;
  text-align: right;
  font-size: 10px;
}
#box{
    display: block;
    margin-left: auto;
  margin-right: auto;
  width: 80%;
    height: 50%;
    background:#f1f1f1;
    border: 2px solid green;
    border-radius: 12px;

}
img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}


/* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
@media (max-width: 600px) {
  .column {
    width: 100%;
  }
}
</style>
<div id="box"><!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <title>Login</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

body {
  text-align: center;
  font-family: Arial, Helvetica, sans-serif;
  color:  seagreen;
  font-size: 25px;
}

/* Style the header */
.header {
  background-color: #f1f1f1;
  padding: 30px;
  text-align: left;
  font-size: 10px;
}

/* Create three equal columns that floats next to each other */
.column {
  /*float: left;*/
  width: 20%;
  padding: 10px;
  height: 300px; /* Should be removed. Only for demonstration */
  border: 2px solid green;
  border-radius: 12px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Style the footer */
.footer {
  background-color: #f1f1f1;
  padding: 10px;
  text-align: right;
  font-size: 10px;
}
#box{
    display: block;
    margin-left: auto;
  margin-right: auto;
  width: 80%;
    height: 50%;
    background:#f1f1f1;
    border: 2px solid green;
    border-radius: 12px;

}
img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}


/* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
@media (max-width: 600px) {
  .column {
    width: 100%;
  }
}
</style>

  <h1> Let's Edit an Existing Caregiver </h1>

<%= render 'form' %>

app/views/caregivers/index.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <title>Login</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

body {
  text-align: center;
  font-family: Arial, Helvetica, sans-serif;
  color:  seagreen;
  font-size: 25px;
}

/* Style the header */
.header {
  background-color: #f1f1f1;
  padding: 30px;
  text-align: left;
  font-size: 10px;
}

/* Create three equal columns that floats next to each other */
.column {
  /*float: left;*/
  width: 20%;
  padding: 10px;
  height: 300px; /* Should be removed. Only for demonstration */
  border: 2px solid green;
  border-radius: 12px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Style the footer */
.footer {
  background-color: #f1f1f1;
  padding: 10px;
  text-align: right;
  font-size: 10px;
}
#box{
    display: block;
    margin-left: auto;
  margin-right: auto;
  width: 80%;
    height: 50%;
    background:#f1f1f1;
    border: 2px solid green;
    border-radius: 12px;

}
img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}


/* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
@media (max-width: 600px) {
  .column {
    width: 100%;
  }
}
</style>
<div id="box">
<h1> All the Caregivers </h1>
</div>
<div id="box">
<% @caregivers.each do |c| %>
<ul><%=link_to c.name, c  %><br></ul>
<% end %>
</div>

app/views/caregivers/new.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <title>Login</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

body {
  text-align: center;
  font-family: Arial, Helvetica, sans-serif;
  color:  seagreen;
  font-size: 25px;
}

/* Style the header */
.header {
  background-color: #f1f1f1;
  padding: 30px;
  text-align: left;
  font-size: 10px;
}

/* Create three equal columns that floats next to each other */
.column {
  /*float: left;*/
  width: 20%;
  padding: 10px;
  height: 300px; /* Should be removed. Only for demonstration */
  border: 2px solid green;
  border-radius: 12px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Style the footer */
.footer {
  background-color: #f1f1f1;
  padding: 10px;
  text-align: right;
  font-size: 10px;
}
#box{
    display: block;
    margin-left: auto;
  margin-right: auto;
  width: 80%;
    height: 50%;
    background:#f1f1f1;
    border: 2px solid green;
    border-radius: 12px;

}
img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}


/* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
@media (max-width: 600px) {
  .column {
    width: 100%;
  }
}
</style>
<div id="box">

<h1> Let's Make a New Caregiver </h1>
</div>
<div id="box">
<%if !!flash[:errors] %>
<% flash[:errors].each do |e| %>
  <p><%= e %><p> <br>
  <%end%>
<%end%>
</div>
<div id="box">
<%= render 'form' %>
</div>

app/views/caregivers/show.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <title>Login</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

body {
  text-align: center;
  font-family: Arial, Helvetica, sans-serif;
  color:  seagreen;
  font-size: 25px;
}

/* Style the header */
.header {
  background-color: #f1f1f1;
  padding: 30px;
  text-align: left;
  font-size: 10px;
}

/* Create three equal columns that floats next to each other */
.column {
  /*float: left;*/
  width: 20%;
  padding: 10px;
  height: 300px; /* Should be removed. Only for demonstration */
  border: 2px solid green;
  border-radius: 12px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Style the footer */
.footer {
  background-color: #f1f1f1;
  padding: 10px;
  text-align: right;
  font-size: 10px;
}
#box{
    display: block;
    margin-left: auto;
  margin-right: auto;
  width: 80%;
    height: 50%;
    background:#f1f1f1;
    border: 2px solid green;
    border-radius: 12px;

}
img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}


/* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
@media (max-width: 600px) {
  .column {
    width: 100%;
  }
}
</style>
<div id="box">

<h1>Welcome to <%=@caregiver.name%>'s Page</h1>
</div>

<div id="box">
<ul> Bio: <%=@caregiver.bio %> <br>
Neighborhood: <%=@caregiver.neighborhood %> <br><br>
<img src=<%=@caregiver.picture_url%>> <br></ul>
</div>

<div id="box">
Services You Provide:<br> <%@caregiver.services.each do |s| %>
<%= s.name %> <br>
<%end%>
</div>

<br>
  <% if session[:user_id] == @caregiver.id %>
<div id="box">

<%=link_to "Update Your Profile or Services", edit_caregiver_path %>
</div>

<div id="box">
<%= button_to('Delete Account', caregiver_path(@caregiver),
          method: "delete", remote: true, data: { confirm: 'Are you sure?', disable_with: 'loading...' }) %>


</div>
<% end %>   

app/views/dogs/edit.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <title>Login</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

body {
  text-align: center;
  font-family: Arial, Helvetica, sans-serif;
  color:  seagreen;
  font-size: 25px;
}

/* Style the header */
.header {
  background-color: #f1f1f1;
  padding: 30px;
  text-align: left;
  font-size: 10px;
}

/* Create three equal columns that floats next to each other */
.column {
  /*float: left;*/
  width: 20%;
  padding: 10px;
  height: 300px; /* Should be removed. Only for demonstration */
  border: 2px solid green;
  border-radius: 12px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Style the footer */
.footer {
  background-color: #f1f1f1;
  padding: 10px;
  text-align: right;
  font-size: 10px;
}
#box{
    display: block;
    margin-left: auto;
  margin-right: auto;
  width: 80%;
    height: 50%;
    background:#f1f1f1;
    border: 2px solid green;
    border-radius: 12px;

}
img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}


/* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
@media (max-width: 600px) {
  .column {
    width: 100%;
  }
}
</style>
<div><div id="box">

<h1> Update your dog's information</h1>
</div>
<div><div id="box">
<%= form_for @dog do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br/>
  <%= f.label :age %>
  <%= f.text_field :age %><br/>
  <%= f.label :size %>; small, medium, or large:
  <%= f.text_field :size %><br/>
  <%= f.label :vet_name %>
  <%= f.text_field :vet_name %><br/>
  <%= f.label :food_name %>
  <%= f.text_field :food_name %><br/>
  <%= f.label :picture %>...insert link to your dog's photo
  <%= f.url_field :img_url %><br/>
  <%= f.submit %>
<% end %>
</div>

app/views/dogs/show.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <title>Login</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

body {
  text-align: center;
  font-family: Arial, Helvetica, sans-serif;
  color:  seagreen;
  font-size: 25px;
}

/* Style the header */
.header {
  background-color: #f1f1f1;
  padding: 30px;
  text-align: left;
  font-size: 10px;
}

/* Create three equal columns that floats next to each other */
.column {
  /*float: left;*/
  width: 20%;
  padding: 10px;
  height: 300px; /* Should be removed. Only for demonstration */
  border: 2px solid green;
  border-radius: 12px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Style the footer */
.footer {
  background-color: #f1f1f1;
  padding: 10px;
  text-align: right;
  font-size: 10px;
}
#box{
    display: block;
    margin-left: auto;
  margin-right: auto;
  width: 80%;
    height: 50%;
    background:#f1f1f1;
    border: 2px solid green;
    border-radius: 12px;

}
img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}


/* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
@media (max-width: 600px) {
  .column {
    width: 100%;
  }
}
</style>
<div><div id="box">
<h1> Who's a good dog??? </h1>
</div>
<div><div id="box">
<ul>
  <b>Name: </b><%= @dog.name %><br>
  <b>Age: </b><%= @dog.age %><br>
  <b>Size: </b><%= @dog.size %><br>
  <b>Veterinarian Name: </b><%= @dog.vet_name %><br>
  <b>Food: </b><%= @dog.food_name %><br>
  <b>Owner: </b><%=@dog.user.full_name %><br>

  <img src=<%= @dog.img_url%> >
  </ul>
</div>
<div><div id="box">
<h2> Appointments </h2>
<ul>
  <% @appointments.each do |a| %>
  <%= a.find_caregiver.name + " - " + a.find_service.name%>
  <% end %>
</ul>
</div>
<div><div id="box">
<%= link_to "back to owner", user_path(@dog.user) %><br>
</div>
<div><div id="box">
<%= link_to "update", edit_dog_path(@dog) %><br>
</div>
<div><div id="box">
<%= button_to "delete", @dog, method: 'delete' %>
</div>

app/views/services/show.erb
<h1> <%=@service.name %></h1>

<p> <%=@service.description %></p>

app/views/users/show.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <title>Login</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

body {
  text-align: center;
  font-family: Arial, Helvetica, sans-serif;
  color:  seagreen;
  font-size: 30px;
}

/* Style the header */
.header {
  background-color: #f1f1f1;
  padding: 30px;
  text-align: left;
  font-size: 10px;
}

/* Create three equal columns that floats next to each other */
.column {
  /*float: left;*/
  width: 20%;
  padding: 10px;
  height: 300px; /* Should be removed. Only for demonstration */
  border: 2px solid green;
  border-radius: 12px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Style the footer */
.footer {
  background-color: #f1f1f1;
  padding: 10px;
  text-align: right;
  font-size: 10px;
}
#box{
    display: block;
    margin-left: auto;
  margin-right: auto;
  width: 80%;
    height: 50%;
    background:#f1f1f1;
    border: 2px solid green;
    border-radius: 12px;

}
img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}


/* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
@media (max-width: 600px) {
  .column {
    width: 100%;
  }
}
</style>


<div><div id="box">

  <p style = "font-family:Arial, Helvetica, sans-serif;font-size:100px; color:MediumSeaGreen;font-style:bold;background:lightgreen;">
    <h1>Our Valued Client:</h1></p


<ul>

  Name:  <%= @user.full_name %><br>
  Email:  <%= @user.email %><br>
  Phone Number:  <%=number_to_phone(@user.phone_number) %><br>
  Neighborhood:  <%= @user.neighborhood %><br>
  </ul>
</div></div>

<div><div id="box">
  <%= link_to "update", edit_user_path(@user) %>
  <%= button_to "delete", @user, method: 'delete' %>

Add A New Dog for this client:
<%=link_to "add new dog", new_dog_path(@dog)%>
<br><br>
</div></div>




<div><div id="box">
<h2> This Client's Dog(s):</h2>
<ul>
    <% @dogs.each do |dog| %>
    <b>Dog:  </b><%=link_to dog.name, dog_path(dog) %><br>
    <h3>This Dog's Appointments:</h3>
      <% dog.appointments.each do |appointment| %>
      Appointment for a <%= link_to appointment.find_service.name, service_path(appointment.service) %> with <%= link_to appointment.find_caregiver.name, caregiver_path(appointment.caregiver) %><br>
      <% end %><br>
    <% end %>
</ul>
</div></div>

<div><div id="box">
<h2>Make a service appointment for your dog</h2>
<%=link_to "30m walk", new30mwalk_path%><br>
<%=link_to "1hr Walk", new1hrwalk_path%><br>
<%=link_to "Overnight Stay", newovernight_path%><br>
<%=link_to "Grooming", newgrooming_path%><br>
<%=link_to "Trip to the Vet", newvet_path%><br>

</div></div>
<%= link_to "Log out", logout_path, method: :delete %>