config/routes.rb
Rails.application.routes.draw do

  get 'startup/index'
  resources :careservices
  resources :services, only: [:show]
  resources :caregivers


  resources :appointments
  resources :dogs
  resources :users

  # to get the login form
    get '/login', to: "sessions#login", as: "login" # does this match REST? where does this go?
    # we need to create a session saying we are logged in
    post '/sessions', to: "sessions#create"
    #get '/logout', to: "sessions#destroy"  as: "logout"

    get 'new30mwalk', to: "appointments#new_30m_walk", as: "new30mwalk"
    get 'new1hrwalk', to: "appointments#new_1hr_walk", as: "new1hrwalk"
    get 'newovernight', to: "appointments#new_overnight", as: "newovernight"
    get 'newgrooming', to: "appointments#new_grooming", as: "newgrooming"
    get 'newvet', to: "appointments#new_vet", as: "newvet"
    delete 'logout', to: "sessions#destroy"

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :dog
  belongs_to :caregiver
  belongs_to :service

def find_dog
  id = self.dog_id
  Dog.all.find_by(id: id)
end

def find_caregiver
  id = self.caregiver_id
  Caregiver.all.find_by(id: id)
end

def find_service
  id = self.service_id
  Service.all.find_by(id: id)
end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def index
    @appointments = Appointment.all
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def new_30m_walk
    session[:service_id] = 6
    @appointment = Appointment.new
    id = session[:user_id]
    @user = User.find_by(id: id)
    @dogs = @user.dogs
    @service = Service.first
    @caregivers = @service.halfwalk_caregivers
    render "new"
  end

  def new_1hr_walk
    session[:service_id] = 7
    @appointment = Appointment.new
    id = session[:user_id]
    @user = User.find_by(id: id)
    @dogs = @user.dogs
    @service = Service.second
    @caregivers = @service.fullwalk_caregivers
    render "new"
  end

  def new_overnight
    session[:service_id] = 8
    @appointment = Appointment.new
    id = session[:user_id]
    @user = User.find_by(id: id)
    @dogs = @user.dogs
    @service = Service.third
    @caregivers = @service.dogsit_caregivers
      render "new"
  end

  def new_grooming
    session[:service_id] = 9
    @appointment = Appointment.new
    id = session[:user_id]
    @user = User.find_by(id: id)
    @dogs = @user.dogs
    @service = Service.fourth
    @caregivers = @service.grooming_caregivers
    render "new"
  end

  def new_vet
    session[:service_id] = 10
    @appointment = Appointment.new
    id = session[:user_id]
    @user = User.find_by(id: id)
    @dogs = @user.dogs
    @service = Service.fifth
    @caregivers = @service.vet_caregivers
    render "new"
  end

  def create
    @appointment = Appointment.create(appointment_params(:dog_id, :caregiver_id, :service_id))
    id = session[:user_id]
    @user = User.find_by(id: id)
    @dogs = @user.dogs
    redirect_to user_path(@user)
  end

  def edit
    @appointment = Appointment.find(params[:id])
  end

  def update
    @appointment = Appointment.find(params[:id])
    @appointment.update(appointment_params)
    redirect_to appointment_path(@appointment)
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy
    redirect_to appointments_path
  end

private

  def appointment_params(*args)
    params.require(:appointment).permit(*args)
  end

end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/edit.erb
<h1>Change or Cancel your Appointment</h1>

app/views/appointments/index.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <title>Login</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

body {
  text-align: center;
  font-family: Arial, Helvetica, sans-serif;
  color:  seagreen;
  font-size: 25px;
}

/* Style the header */
.header {
  background-color: #f1f1f1;
  padding: 30px;
  text-align: left;
  font-size: 10px;
}

/* Create three equal columns that floats next to each other */
.column {
  /*float: left;*/
  width: 20%;
  padding: 10px;
  height: 300px; /* Should be removed. Only for demonstration */
  border: 2px solid green;
  border-radius: 12px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Style the footer */
.footer {
  background-color: #f1f1f1;
  padding: 10px;
  text-align: right;
  font-size: 10px;
}
#box{
    display: block;
    margin-left: auto;
  margin-right: auto;
  width: 80%;
    height: 50%;
    background:#f1f1f1;
    border: 2px solid green;
    border-radius: 12px;

}
img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}


/* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
@media (max-width: 600px) {
  .column {
    width: 100%;
  }
}
</style>
<div><div id="box">

<h1> All of the appointments in our system: </h1>
</div>
<br>
<div><div id="box">
#Appointments by dog:
</div>
<br>
<div><div id="box">
#Appointments by caregiver:
</div>

app/views/appointments/new.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <title>Login</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

body {
  text-align: center;
  font-family: Arial, Helvetica, sans-serif;
  color:  seagreen;
  font-size: 25px;
}

/* Style the header */
.header {
  background-color: #f1f1f1;
  padding: 30px;
  text-align: left;
  font-size: 10px;
}

/* Create three equal columns that floats next to each other */
.column {
  /*float: left;*/
  width: 20%;
  padding: 10px;
  height: 300px; /* Should be removed. Only for demonstration */
  border: 2px solid green;
  border-radius: 12px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Style the footer */
.footer {
  background-color: #f1f1f1;
  padding: 10px;
  text-align: right;
  font-size: 10px;
}
#box{
    display: block;
    margin-left: auto;
  margin-right: auto;
  width: 80%;
    height: 50%;
    background:#f1f1f1;
    border: 2px solid green;
    border-radius: 12px;

}
img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}


/* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
@media (max-width: 600px) {
  .column {
    width: 100%;
  }
}
</style>
<div><div id="box">
<h1>Create a new <%=@service.name.capitalize%> for your dog!</h1>
</div>
<div><div id="box">
<%= form_for @appointment do |f| %>
<%= f.hidden_field :service_id, :value => session[:service_id] %>
Choose Your Dog...   <%=f.collection_select :dog_id, @dogs, :id, :name %> <br>
Choose Your Caregiver... <%= f.collection_select :caregiver_id, @caregivers, :id, :name %> <br>
<%=f.submit%>
  <%end%>
  </div>

app/views/appointments/show.erb
<h1>Here are your Appointments</h1>
<%= link_to @appointment.dog.name, dog_path(@appointment.dog) %>